version: "3.9"
services:
  db:
    image: mysql:8.0.3
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: migration
      MYSQL_USER: kudu
      MYSQL_PASSWORD: kudu
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  web:
    image: library/nginx:1.13.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7-fpm
    ports:
      - 9000:9000
    volumes:
      - ./web:/usr/share/nginx/html
  phpmyadmin:
    image: phpmyadmin:5.0.4
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80

